### ISSUE TITLE
not working with react native 0.69.4, Execution failed for task ':react-native-screens:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by xiongemi** [software-mansion/react-native-screens#1551]
## Description

update to react-native 0.69.4, got an error for react-native-screen
```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
tmp/node_modules/react-native-screens/android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerDelegate.java:18: error: duplicate class: com.facebook.react.viewmanagers.RNSScreenStackHeaderConfigManagerDelegate
public class RNSScreenStackHeaderConfigManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & RNSScreenStackHeaderConfigManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
       ^
tmp/node_modules/react-native-screens/android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderSubviewManagerInterface.java:15: error: duplicate class: com.facebook.react.viewmanagers.RNSScreenStackHeaderSubviewManagerInterface
public interface RNSScreenStackHeaderSubviewManagerInterface<T extends View> {
       ^
tmp/node_modules/react-native-screens/android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenStackManagerDelegate.java:17: error: duplicate class: com.facebook.react.viewmanagers.RNSScreenStackManagerDelegate
public class RNSScreenStackManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & RNSScreenStackManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
       ^
tmp/node_modules/react-native-screens/android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenManagerDelegate.java:19: error: duplicate class: com.facebook.react.viewmanagers.RNSScreenManagerDelegate
public class RNSScreenManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & RNSScreenManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
       ^
tmp/node_modules/react-native-screens/android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderConfigManagerInterface.java:15: error: duplicate class: com.facebook.react.viewmanagers.RNSScreenStackHeaderConfigManagerInterface
public interface RNSScreenStackHeaderConfigManagerInterface<T extends View> {
       ^
tmp/node_modules/react-native-screens/android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenStackHeaderSubviewManagerDelegate.java:17: error: duplicate class: com.facebook.react.viewmanagers.RNSScreenStackHeaderSubviewManagerDelegate
public class RNSScreenStackHeaderSubviewManagerDelegate<T extends View, U extends BaseViewManagerInterface<T> & RNSScreenStackHeaderSubviewManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
       ^
tmp/node_modules/react-native-screens/android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenStackManagerInterface.java:14: error: duplicate class: com.facebook.react.viewmanagers.RNSScreenStackManagerInterface
public interface RNSScreenStackManagerInterface<T extends View> {
       ^
tmp/node_modules/react-native-screens/android/build/generated/source/codegen/java/com/facebook/react/viewmanagers/RNSScreenManagerInterface.java:16: error: duplicate class: com.facebook.react.viewmanagers.RNSScreenManagerInterface
public interface RNSScreenManagerInterface<T extends View> {
       ^
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

## Steps To Reproduce

1.

## Platform

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Architecture

- [ ] Paper
- [ ] Fabric

## Workflow

- [ ] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |         |
| @react-navigation/native               |         |
| @react-navigation/native-stack         |         |
| react-native-screens                   |         |
| react-native-safe-area-context         |         |
| react-native-gesture-handler           |         |
| react-native-reanimated                |         |
| expo                                   |         |

**Comment by kkafar** [comment]
Hi @xiongemi 
From my experience running `./gradlew clean` / removing android build directory + re-installing node modules should fix the problem. 
If the problem persists, it would be great if you filled out the issue form.

**Comment by kkafar** [comment]
So it seems that this issue occurs when you play with Paper & Fabric simultaneously, as both architectures use these interfaces but from different "source directories". In case of Fabric, these are auto generated, while for Paper they are shipped with the codebase of the library. When both: auto-generated and shipped interfaces are present Paper build fails with presented error. 

Cleaning Android build directory resolves the issue.
