### ISSUE TITLE
iOS compile failes on react native 0.78.0

### ISSUE THREAD

**Issue by jonluca** [software-mansion/react-native-screens#2716]
### Description

When attempting to install react-native-screens in a new react-native project we're seeing a compilation error

- no member named 'parentShadowView' in 'facebook::react::ShadowViewMutation'
Refer to "Xcode Logs" below for additional, more detailed logs.

```
CompileC /Users/expo/Library/Developer/Xcode/DerivedData/Weights-dqqzqcrfobomtkdpsjeqmpbzsjar/Build/Intermediates.noindex/ArchiveIntermediates/Weights/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/RNScreens.build/Objects-normal/arm64/RNSScreenRemovalListener.o /Users/expo/workingdir/build/node_modules/react-native-screens/cpp/RNSScreenRemovalListener.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNScreens' from project 'Pods')
```

### Steps to reproduce

Attempt to build with react native 0.78.0 on v4.8.0

### Snack or a link to a repository

https://expo.dev/accounts/weights/projects/weights/builds/0922c63e-e6cb-42df-99ad-0a01faf27ea7

### Screens version

4.8.0

### React Native version

0.78.0

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey, support for 0.78 comes with 4.9.0 (currently 4.9.0-beta.0 is released).
