### ISSUE TITLE
Crash after upgrading to 2.10: undefined is not a function (near '...navigation.addListener...')

### ISSUE THREAD

**Issue by diego-paired** [software-mansion/react-native-screens#588]
![image](https://user-images.githubusercontent.com/55058765/89405047-dae44e80-d712-11ea-84de-f328e1f92209.png)

Downgrading to 2.09 makes the error go away.

**Comment by WoLewicki** [comment]
Should be fixed in 2.10.1. Can you check?

**Comment by diego-paired** [comment]
@WoLewicki It works again, thanks!
