### ISSUE TITLE
CMake Error while building react native android app in android studio.

### ISSUE THREAD

**Issue by jet2018** [software-mansion/react-native-screens#2409]
### Description

ERROR:- 
Target "rnscreens" links to target "ReactAndroid::react_render_consistency"
but the target was not found.  Perhaps a find_package() call is missing for
an IMPORTED target, or an ALIAS target is missing?
CMake Error at CMakeLists.txt:6 (add_library):
Target "rnscreens" links to target
"ReactAndroid::react_performance_timeline" but the target was not found.
Perhaps a find_package() call is missing for an IMPORTED target, or an
ALIAS target is missing?
CMake Error at CMakeLists.txt:6 (add_library):
Target "rnscreens" links to target
"ReactAndroid::react_render_observers_events" but the target was not found.
Perhaps a find_package() call is missing for an IMPORTED target, or an
ALIAS target is missing?

INFO
System:
  OS: macOS 15.0.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 45.36 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.0
    path: ~/.nvm/versions/node/v20.15.0/bin/node
  Yarn:
    version: 4.4.1
    path: /usr/local/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.0/bin/npm
  Watchman:
    version: 2024.07.01.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/jet/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1. Upgrade from react native 0.74.6 to 0.75.4

### Snack or a link to a repository

https://react-native-community.github.io/upgrade-helper/?from=0.74.6&to=0.75.4

### Screens version

^3.34.0 (latest)

### React Native version

0.75.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Sumsung Galaxy s23 Ultra(Android 14)

### Acknowledgements

Yes

**Comment by jet2018** [comment]
This issue only happens upon upgrades. Therefore, there might not be a way to provide a snack here.

**Comment by kkafar** [comment]
@jet2018,

this indicates that the upgrade was not done completely (maybe there are some missing changes) or there is some cache (cmake especially) present. 

I would suggest to try simply removing all the cache you can, including all `.cxx` directories.

`rm -fr node_modules android/build android/app/build android/app/.cxx`.

I don't think we will be able to help much more w/o the reproducer, especially that we're working now on 0.75.4 ourselves & we haven't seen the issue you encountered.

**Comment by laurensk** [comment]
I have the same issue on 0.76 with 3.34.0

**Comment by jet2018** [comment]
I cleared all caches, generated build and gradle folders, performed a clean app installation, and the issue disappeared. 

So, am not sure what exactly resolved it, but removing caches might be what you need.

**Comment by Jakub-Plan-d-k** [comment]
@laurensk same

**Comment by coder-xiaomo** [comment]
Facing the same issue in react-native 0.76.0 with the new arch enabled (default). i guess maybe the new arch caused this problem?
And maybe issue #2441 #2442 #2443 is the similar problem(not quite sure).

**Comment by Jakub-Plan-d-k** [comment]
@coder-xiaomo  definitely, once I turned the new arch off, the build went smoothly

**Comment by kkafar** [comment]
Is someone able to provide reproduction of this issue? Note that we've released 3.35.0 just few minutes ago. You could try it out as it has support for RN 0.76

**Comment by laurensk** [comment]
Seems to work with 3.35.0.

Still don't have a working build due to open issues with other libraries but the error from react-native-screens seems to be gone.

**Comment by kkafar** [comment]
@laurensk, if you're blocked by safe-area-context see the patch we're using in our example app: https://github.com/software-mansion/react-native-screens/tree/main/FabricExample/patches

**Comment by kkafar** [comment]
I'll proceed with closing the issue, as it has been resolved for the original author & we have report that 3.35.0 could have helped out here. 

If the issue persists please attach any helpful information & tag me, I'll reopen if necessary.

**Comment by Jakub-Plan-d-k** [comment]
@kkafar 
So I have just tried compiling my app after clearing the cache and enabling the new arch. The original issue seems to be resolved :) (ofc now I have an issue with another library, but that's a different story)

**Comment by shirakaba** [comment]
@kkafar's suggested cleanup command bailed me out when I was facing an unrelated duplicate symbols issue (but I can recommend as a sanity check for anyone facing codegen issues). In my case, I didn't need to clear out my `node_modules`, just my app build.

```diff
- rm -fr node_modules android/build android/app/build android/app/.cxx.
+ rm -fr android/build android/app/build android/app/.cxx.
```

**Comment by camboYY** [comment]
with new architecture enabled, this issue still exist.

**Comment by Mihai-github** [comment]
+1 cannot get rid of the error

**Comment by gomdolkim** [comment]
+1

**Comment by Mohangupta495** [comment]
I found a workaround that fixed the CMake error in my React Native project. Sharing the steps here in case it helps others:

1. Remove all dependencies from `package.json` **except** `react` and `react-native`.
2. Run `yarn install` or `npm install`.
3. Open the project in Android Studio and let it sync completely.
4. Once the sync is successful, restore the removed dependencies in `package.json`.
5. Run `yarn install` or `npm install` again.
6. Sync the project again in Android Studio.

This process solved the issue for me. Hope it helps someone else too.

**Comment by Bilalwarind** [comment]
please try this fix: https://github.com/software-mansion/react-native-reanimated/issues/7924

**Comment by harun-alrosyid** [comment]
You can try this for solve this issue 
https://github.com/harun-alrosyid/developer-tips/blob/main/cmake-error-reactnative-0.80.1/cmake-error-reactnative-0.80.1.md
