### ISSUE TITLE
RN 59.x - AndroidX libraries cannot be found

### ISSUE THREAD

**Issue by jeveloper** [software-mansion/react-native-screens#126]
Fairly general question

What is causing these errors:

cannot find symbol on all androidx imports

Java 10, Gradle build version 3.4.1 , RN 0.59.10

Thanks!

**Comment by jannainm** [comment]
Not sure this really helps anyone but I was not able to build with `1.0.0-alpha.23` so in my package.json I pinned it to version 22 specifically for now, `"react-native-screens": "1.0.0-alpha.22"`. I'm also on RN 0.59.10 and I believe we need to be on 0.60 for android x supported libs.

**Comment by jhoanborges** [comment]
@jannainm a downgrade to "react-native-screens": "1.0.0-alpha.22" did the trick thank you

**Comment by thekevinbrown** [comment]
I didn't have `react-native-screens` as a direct dependency, so I ran

```
$ npm i react-native-screens@1.0.0-alpha.22 --save-exact
```

and am now able to build.

**Comment by scerelli** [comment]
`yarn add --dev jetify`

then in you `package.json` scripts add:
`"postinstall": "jetify"`
then `yarn jetify`

then build

**Comment by WoLewicki** [comment]
It looks like the issue is outdated, I am closing it then. Feel free to comment if I am wrong.
