### ISSUE TITLE
(0 , _reactNativeScreens.enableScreens) is not a function

### ISSUE THREAD

**Issue by mikeRChambers610** [software-mansion/react-native-screens#508]
Anyone getting issue below?? I've placed the import in the app.js file and I do not have any screens rendered here.

(0 , _reactNativeScreens.enableScreens) is not a function

**Comment by WoLewicki** [comment]
Can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by nero2009** [comment]
Just upgraded from expo sdk 35 to sdk 37 and I get this error 
<img width="378" alt="Screenshot 2020-05-14 at 02 27 40" src="https://user-images.githubusercontent.com/29065069/81882393-91102000-958a-11ea-87c1-fa83098e4e58.png">
I suspect this is caused by the `enableScreens()` call in `line 38` of my `index.js` as seen although not clearly in the above stacktrace

<img width="990" alt="Screenshot 2020-05-14 at 02 33 33" src="https://user-images.githubusercontent.com/29065069/81883032-1e07a900-958c-11ea-9df6-77d2501644ac.png">

I had to update `react-native-screens` when I migrated from sdk 35 to 37 and this update deprecated `useScreens` and replaced it with `enableScreens`

**Comment by WoLewicki** [comment]
Can you provide a repo with minimal configuration needed to reproduce the issue?

**Comment by nero2009** [comment]
I was able to fix this and for me the error not caused by `react-native-screens` `enableScreens`, it was actually caused by the `bugsnag()` on line 39, SDK 37 uses a different version of bugsnag from sdk 35 so instead of initialising it with `bugsnag()` I used `bugsnag.start()`.

That fixed the problem for me

**Comment by gauravsbagul** [comment]
I am having same issue

**Comment by WoLewicki** [comment]
@gauravsbagul can you provide a repo/snack with minimal configuration needed to reproduce the issue?

**Comment by WoLewicki** [comment]
I am closing it due to no response in more than 30 days. Feel free to comment to reopen it.

**Comment by ApWin** [comment]
I'm having same issue ((

**Comment by kacperkapusciak** [comment]
@ApWin we would like to help but we need a way to reproduce the issue. Could you provide a simple code snippet that reproduces this?
