### ISSUE TITLE
No member named 'parentShadowView' in 'facebook::react::ShadowViewMutation'

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-screens#2594]
### Description

I'm trying to build react-native 0.78 nightly, but react-native-screens doesn't seem to support RN 78 yet because there were some changes to Yoga/Fabric APIs which RNScreens seems to rely on:

```diff
- No member named 'parentShadowView' in 'facebook::react::ShadowViewMutation'
```

![image](https://github.com/user-attachments/assets/51cf4b9f-d123-4a1c-849c-6f8ebd4a129a)

### Steps to reproduce

1. Create a new react native app with RN 78 nightly / main
2. Install react-native-screens
3. Build

### Snack or a link to a repository

https://github.com/mrousavy/nitro/pull/454

### Screens version

4.4.0

### React Native version

0.78.0@nightly

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by mrousavy** [comment]
Same also happens here in `RNSScreenStack.mm` line 1220:

```diff
- No member named 'parentShadowView' in 'facebook::react::ShadowViewMutation'
```

![Screenshot 2024-12-30 at 13 47 00](https://github.com/user-attachments/assets/e03e2cad-03b1-48fe-a448-ea9cd0cf7010)


But I think this can be replaced with `parentTag`.

**Comment by kkafar** [comment]
Thanks for reporting this. We won't be working on 0.78 support for at least few more weeks now, but this is great heads up. Thanks

**Comment by kkafar** [comment]
I've merged https://github.com/software-mansion/react-native-screens/pull/2595 into PR with 0.78 support. I'll close the issue as this is not a "regular issue".

**Comment by gagtic** [comment]
> ### Description
> 
> I'm trying to build react-native 0.78 nightly, but react-native-screens doesn't seem to support RN 78 yet because there were some changes to Yoga/Fabric APIs which RNScreens seems to rely on:
> 
> - No member named 'parentShadowView' in 'facebook::react::ShadowViewMutation'
> ![image](https://github.com/user-attachments/assets/51cf4b9f-d123-4a1c-849c-6f8ebd4a129a)
> 
> ### Steps to reproduce
> 
> 1. Create a new react native app with RN 78 nightly / main
> 2. Install react-native-screens
> 3. Build
> 
> ### Snack or a link to a repository
> 
> [mrousavy/nitro#454](https://github.com/mrousavy/nitro/pull/454)
> 
> ### Screens version
> 
> 4.4.0
> 
> ### React Native version
> 
> 0.78.0@nightly
> 
> ### Platforms
> 
> iOS
> 
> ### JavaScript runtime
> 
> Hermes
> 
> ### Workflow
> 
> React Native (without Expo)
> 
> ### Architecture
> 
> Fabric (New Architecture)
> 
> ### Build type
> 
> Debug mode
> 
> ### Device
> 
> iOS simulator
> 
> ### Device model
> 
> _No response_
> 
> ### Acknowledgements
> 
> Yes

I tried using `parentTag` here instead of `parentShadowView`, but still getting errors.

Also I have the latest build for react-native-screens and this is still reproducing in it. `4.7.0-beta.1`

**Comment by ajlee4** [comment]
I have the same problem, is there any solution? @mrousavy

**Comment by ajlee4** [comment]
maybe you have found a solution to the problem? @gagtic

**Comment by kkafar** [comment]
I'll be working on support for 0.78 after release of 4.7.0 - that **should** be early next week.

**Comment by ajlee4** [comment]
Thank you, we will be looking forward to it.

**Comment by tuan782000** [comment]
> where is parentShadowView change to oldChildShadowView, in my case fix the errors

It's work for me

**Comment by TweetyBoop1990** [comment]
> > where is parentShadowView change to oldChildShadowView, in my case fix the errors
> 
> It worked for me

What exactly did you change to make it work?

**Comment by tuan782000** [comment]
I modified around 15 to 20 instances where parentShadowView was replaced with oldChildShadowView. I don’t remember the exact locations, so you might need to dig deeper. Xcode is also showing warnings related to this.

**Comment by manish0707** [comment]
Is there any proper fix for this?

**Comment by c100k** [comment]
The proper fix is to upgrade to 4.9.0 : https://github.com/software-mansion/react-native-screens/releases/tag/4.9.0

Note that there is a similar issue with react-native-reanimated that is currently being addressed : https://github.com/software-mansion/react-native-reanimated/issues/7061

Let's be patient, especially when the maintainers do this on their free time.

**Comment by joshwinter** [comment]
I'm still seeing this issue in 4.9.0.

**Comment by daviddamilola** [comment]
I still see it is 4.9.0 also

**Comment by armanshep** [comment]
I am seeing this issue in 4.9.0

**Comment by kkafar** [comment]
I'll be releasing patch version in few moments. I'll contain #2737

**Comment by kkafar** [comment]
I've just released 4.9.1 that should solve the problem. Let me know whether it works for you!

**Comment by adam1929** [comment]
Hi @kkafar I'm facing this issue too with 4.9.1. Sorry.
I'm upgrading app to RN 0.78.0
I can see build issue in
`LayoutAnimationsUtils`
```
void Node::applyMutationToIndices(ShadowViewMutation mutation) {
  if (tag != mutation.parentShadowView.tag) {   // <- No member named 'parentShadowView' in 'facebook::react::ShadowViewMutation'
    return;
  }
```

**Comment by kkafar** [comment]
@adam1929, sorry, but `LayoutAnimationsUtils` are unrelated to `react-native-screens`. This is either `react-native` or `react-native-reanimated` code & you should seek help there.

**Comment by stereodenis** [comment]
it's still reproduced in 4.11.0-beta.2

<img width="1002" alt="Image" src="https://github.com/user-attachments/assets/415f0660-568f-460a-996b-ac9122482f66" />

**Comment by kkafar** [comment]
@stereodenis can you provide reproduction? Right now my belief is that you have mismatched react-native & `react-native-screens` versions & I won't dig into it.

**Comment by stereodenis** [comment]
@kkafar I will try today

"react-native": "0.77.2",
"react-native-screens": "4.11.0-beta.2",

**Comment by kkafar** [comment]
The dependencies version do look good though. Ping me if we have a repro - I'll look into this.

**Comment by ashfaqdevdksa** [comment]
@kkafar Is there any proper fix release for this on the newer versions ? 
Still getting same error react-native 0.79.3 react-native-screens 4.11.1

<img width="1477" alt="Image" src="https://github.com/user-attachments/assets/205d8efb-5048-4a63-8071-09710f70121f" />

**Comment by expertzappdev** [comment]
got same error my react native version is -    "react-native": "0.76.5", and     "react-native-screens": "^4.13.1",

<img width="1313" height="480" alt="Image" src="https://github.com/user-attachments/assets/d4f3b007-2f43-4b8b-b0b5-def7b0b3cc84" />

**Comment by hantongliu** [comment]
The same react-native: 0.77.0 and react-native-screens: 4.13.1

**Comment by AdrishS-AW** [comment]
My Setup:

```
"react-native": "0.76.5",
"react-native-screens": "4.6.0",
"react-native-reanimated": "^3.16.0",
```

This has been working fine for last 6 months then just yesterday I started facing this issue after running 
```
yarn install
pod install --repo-update
```

Updating to newer versions didn't work and I also tried cleaning caches, deleting derived data, reinstalling node modules and pods etc, and even restarted my pc. So basically none of above solutions worked for me.

Then I downgraded reanimated to v.3.14.0 which made the app to run (build successful) however my bottom sheet broke (I am using @gorhom/bottomsheet)

So I upgraded back to "react-native-reanimated": "3.16.1". Note that I removed version range selector and went with minimum patch version I could and somehow this worked. I have no idea what sorcery is this 😖
