### ISSUE TITLE
cannot find symbol import com.facebook.react.views.text.ReactTypefaceUtils for RN 0.60.5

### ISSUE THREAD

**Issue by finntenzor** [software-mansion/react-native-screens#1230]
## Description

I'm using react-native-screens 3.1.1 and react-native 0.60.5. When I compile, it shows:

```
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
D:\Projects\Bestdet\Bestdet\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:26: error: cannot find symbol
import com.facebook.react.views.text.ReactTypefaceUtils;
                                    ^
  symbol:   class ReactTypefaceUtils
  location: package com.facebook.react.views.text
D:\Projects\Bestdet\Bestdet\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:247: error: cannot find symbol
        Typeface titleTypeface = ReactTypefaceUtils.applyStyles(
                                 ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
D:\Projects\Bestdet\Bestdet\node_modules\react-native-screens\android\src\main\java\com\swmansion\rnscreens\ScreenStackHeaderConfig.java:377: error: cannot find symbol
    mTitleFontWeight = ReactTypefaceUtils.parseFontWeight(fontWeightString);
                       ^
  symbol:   variable ReactTypefaceUtils
  location: class ScreenStackHeaderConfig
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
```

### Screenshots

![image](https://user-images.githubusercontent.com/7535112/144810551-55de2608-d4cc-4571-97e8-9429d1c10a65.png)

## Steps To Reproduce

1. Create a new React Native application (0.60.5)
2. Add react-native-screens as dependency (3.1.1)
3. Run `react-native run-android` (in yarn command)

### Expected behavior

The application builds.

### Actual behavior

error: cannot find symbol

## Platform

- [ ] iOS
- [ ] Android
- [ ] Web
- [x] Windows
- [ ] tvOS

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |      0.60.5   |
| @react-navigation/native               |    3.8.4     |
| @react-navigation/native-stack         |    not used    |
| react-native-screens                   |     3.1.1    |
| react-native-safe-area-context         |    not used     |
| react-native-gesture-handler           |    1.10.3     |
| react-native-reanimated                |    1.13.3     |
| expo                                   |    not used   |

This projects is about 1~2 years ago and I'm trying to fix it. My schedule doesn't seem to allow me to upgrade the React-Native version, which could cause problems with other dependent libraries. Is there a way to just update or degrade a dependency library, or to patch a dependency library?

**Comment by kacperkapusciak** [comment]
Hi @finntenzor,
`react-native-screens` `>=3.0.0` won't compile with `react-native` older than `0.62`

 In your case, it looks like downgrading `screens` to version `2.18.1` should resolve your problem
 
 ```bash
 yarn add react-native-screens@2.18.1
 ```
 
Cheers

**Comment by finntenzor** [comment]
> 

Hi @kacperkapusciak ,
Thank you so much. It's work for me!
